require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
use_modular_headers!

target 'Posty' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  # 핵심 기능만 설치 (Firebase 완전 제외)
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  
  # 소셜 로그인 (Firebase 없이)
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'
  pod 'kakao-login', :path => '../node_modules/@react-native-seoul/kakao-login'
  pod 'RNNaverLogin', :path => '../node_modules/@react-native-seoul/naver-login'
  pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'
  
  # 기타 필수 기능
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNCClipboard', :path => '../node_modules/@react-native-clipboard/clipboard'
  
  # 명시적으로 boost 추가 (설치 문제 해결)
  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix module redefinition
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        
        # C++20 설정 (React Native 0.74.5+ 호환성)
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        # 모든 타겟에 GNU C 확장 적용 (typeof 등 지원)
        config.build_settings['GCC_C_LANGUAGE_STANDARD'] = 'gnu99'
        
        # 모듈 중복 정의 경고 무시
        config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -Xcc -Wno-error=non-modular-include-in-framework-module'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        # Xcode 버전 호환성을 위해 컴파일러 플래그 수정
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-error'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -Wno-error'
      end
    end
    
    # ReactCommon 모듈 충돌 해결
    react_common_path = File.join(installer.sandbox.root, 'Headers/Public/ReactCommon')
    if File.exist?(react_common_path)
      Dir.glob(File.join(react_common_path, '*.modulemap')).each do |modulemap|
        if File.basename(modulemap) == 'React-RuntimeApple.modulemap'
          File.delete(modulemap)
        end
      end
    end
  end
end
