import React from 'react';
import { ScrollView, Text, StyleSheet, SafeAreaView, View, TouchableOpacity } from 'react-native';
import { useTranslation } from 'react-i18next';
import { SafeIcon } from '../../utils/SafeIcon';
import { COLORS, SPACING, FONT_SIZES } from '../../utils/constants';
import { useAppTheme } from '../../hooks/useAppTheme';

interface TermsOfServiceScreenENProps {
  onBack: () => void;
  onNavigate?: (screen: string) => void;
}

const TermsOfServiceScreen_EN: React.FC<TermsOfServiceScreenENProps> = ({
  onBack,
  onNavigate,
}) => {
  const { colors } = useAppTheme();
  const { t } = useTranslation();
  const styles = createStyles(colors);

  const lastUpdated = "January 1, 2024";

  const staticContent = `# Terms of Service

Effective Date: January 1, 2024

Company Name: Tinrobot Studio

## Article 1 (Purpose)

These Terms and Conditions aim to stipulate the terms and procedures for using the AI-based SNS content creation service "Posty" (hereinafter referred to as "Service") provided by Tinrobot Studio (hereinafter referred to as "Company"), as well as the rights, obligations, responsibilities, and other necessary matters between the Company and users.

## Article 2 (Definition of Terms)

The definitions of terms used in these Terms are as follows:

**"Service"** means all services related to AI-based SNS content creation and management provided by the Company.

**"User"** means a person who uses the Service provided by the Company in accordance with these Terms.

**"Content"** means all forms of information created, stored, and shared by users through the Service.

**"AI-Generated Content"** means text, image analysis results, etc., generated through the artificial intelligence features of the Service.

## Article 3 (Effect and Amendment of Terms)

These Terms shall become effective for all users who wish to use the Service.

The Company may amend these Terms as necessary within the scope that does not violate relevant laws, and the amended Terms shall be announced through notices within the Service.

If a user does not agree to the amended Terms, they may discontinue using the Service and withdraw.

## Article 4 (Provision of Service)

The services provided by the Company are as follows:

**AI-based SNS content creation service**

**SNS trend analysis and insights provision**

**User writing style analysis**

**SNS account integration and post management**

**Other services that the Company additionally develops or provides through partnerships**

## Article 5 (Use of Service)

Users may use the Service according to the procedures established by the Company.

Users must comply with relevant laws when using the Service.

Users must not create content that infringes on the rights of others or is contrary to public order and morals.

## Article 6 (Personal Information Protection)

The Company does its best to protect users' personal information.

Matters concerning the collection, use, and provision of personal information are subject to the Company's Privacy Policy.

The Company does not provide personal information to third parties without user consent.

## Article 7 (Rights and Responsibilities of Content)

The copyright of content created by users belongs to the users.

Content generated by AI can be freely used, modified, and distributed by users.

Users are responsible for all content they create.

The Company may analyze users' content for service improvement, but this is used only in anonymized form.

## Article 8 (Restriction of Service Use)

The Company may restrict service use in the following cases:

When these Terms are violated

When content that infringes on the rights of others is created

When normal operation of the Service is disrupted

When relevant laws are violated

## Article 9 (Disclaimer)

The Company is not responsible for service interruptions due to force majeure such as natural disasters or wars.

The Company does not guarantee the accuracy of information or materials obtained by users through the Service.

The Company does not intervene in disputes between users or between users and third parties.

## Article 10 (Governing Law and Jurisdiction)

These Terms shall be governed by and construed in accordance with the laws of the Republic of Korea.

Disputes arising from the use of the Service shall be subject to the exclusive jurisdiction of the court having jurisdiction over the location of the Company's headquarters.

• --

Contact: getposty@gmail.com

Privacy Officer: privacy@getposty.ai

## Article 12 (Use of Artificial Intelligence Technology)

1. **AI Technology Utilization**

   - This Service uses artificial intelligence technology based on OpenAI's GPT models to provide the following services:

     * Automatic content generation

     * Text improvement and refinement

     * Photo-based content creation

     * Personalized writing recommendations

2. **Nature of AI-Generated Content**

   - We do not guarantee the accuracy, appropriateness, completeness, or copyright compliance of AI-generated content.

   - Users should use AI-generated content for reference only and must review and take responsibility for the content before final use.

   - Users must acknowledge that AI-generated content may infringe on third-party rights or contain inappropriate material.

3. **Data Processing**

   - User-input data such as text and photos may be transmitted to external AI service providers (such as OpenAI) for AI service provision.

   - Transmitted data is used only for service provision purposes and is processed in accordance with the Privacy Policy.

4. **Service Changes**

   - The Company may modify AI functions after prior notice for AI model updates, changes, or service improvements.

   - New features may be added or existing features may be changed according to AI technology developments.

5. **Disclaimer**

   - The Company is not responsible for direct or indirect damages arising from AI-generated content.

   - Users bear all legal responsibility for the use of AI-generated content.`;

  const renderStaticContent = () => {
    const content = staticContent.split('\n\n').map((paragraph, index) => {
      if (paragraph.startsWith('#')) {
        const level = paragraph.match(/^#+/)?.[0].length || 1;
        const text = paragraph.replace(/^#+\s*/, '');
        return (
          <Text
            key={index}
            style={level === 1 ? styles.sectionTitle : styles.subTitle}
          >
            {text}
          </Text>
        );
      } else if (paragraph.startsWith('•') || paragraph.startsWith('-') || paragraph.startsWith('*')) {
        return (
          <Text key={index} style={styles.listItem}>
            {paragraph}
          </Text>
        );
      } else if (paragraph.trim()) {
        return (
          <Text key={index} style={styles.paragraph}>
            {paragraph}
          </Text>
        );
      }
      return null;
    }).filter(Boolean);

    return content;
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={onBack} style={styles.backButton}>
          <SafeIcon name="arrow-back" size={24} color={colors.text.primary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>
          {t('documents.termsOfService')}
        </Text>
        <View style={styles.headerRight} />
      </View>

      <ScrollView
        style={styles.content}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.contentContainer}
      >
        <Text style={styles.lastUpdated}>
          {t('documents.lastUpdated')}: {lastUpdated}
        </Text>

        {renderStaticContent()}

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            These Terms are effective from {lastUpdated}.
          </Text>
          <Text style={styles.footerText}>
            Contact: getposty@gmail.com
          </Text>
        </View>

        <View style={styles.bottomSpace} />
      </ScrollView>
    </SafeAreaView>
  );
};

const createStyles = (colors: typeof COLORS) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.md,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      padding: SPACING.sm,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.text.primary,
      flex: 1,
      textAlign: 'center',
    },
    headerRight: {
      width: 40,
      alignItems: 'flex-end',
    },
    content: {
      flex: 1,
    },
    contentContainer: {
      paddingHorizontal: SPACING.lg,
      paddingTop: SPACING.lg,
    },
    lastUpdated: {
      fontSize: FONT_SIZES.small,
      color: colors.text.tertiary,
      marginBottom: SPACING.xl,
      textAlign: "center",
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text.primary,
      marginBottom: SPACING.md,
    },
    subTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.text.primary,
      marginTop: SPACING.md,
      marginBottom: SPACING.sm,
    },
    paragraph: {
      fontSize: FONT_SIZES.medium,
      color: colors.text.secondary,
      lineHeight: 22,
      marginBottom: SPACING.sm,
    },
    listItem: {
      fontSize: FONT_SIZES.medium,
      color: colors.text.secondary,
      lineHeight: 22,
      marginBottom: SPACING.sm,
      paddingLeft: SPACING.md,
    },
    footer: {
      marginTop: SPACING.xxl,
      paddingTop: SPACING.xl,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      alignItems: "center",
    },
    footerText: {
      fontSize: FONT_SIZES.small,
      color: colors.text.tertiary,
      marginBottom: SPACING.sm,
      textAlign: "center",
    },
    bottomSpace: {
      height: SPACING.xxl,
    },
  });

export default TermsOfServiceScreen_EN;