name: Keep Server Warm

on:
  schedule:
    # 매 5분마다 실행 (UTC 기준)
    - cron: '*/5 * * * *'
  # 수동 실행도 가능하게
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping AI Server
      run: |
        echo "Pinging Posty AI Server..."
        curl -s https://posty-server.vercel.app/api/health || echo "Server might be sleeping"
        
    - name: Ping Trends API
      run: |
        echo "Pinging Trends API..."
        curl -s https://posty-api-v2.vercel.app/api/health || echo "Trends API might be sleeping"
